name: Build App, Run Unit Tests, Run UI Tests And Deploy to Render

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Start the application
      run: npm start &
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "t_stoyanov"

  ui-tests:
    runs-on: ubuntu-latest
    needs: build-unit-test

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies 
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Start the application
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui
    
  deploy:
    runs-on: ubuntu-latest
    needs: ui-tests
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true