name: Build App, Run Unit Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Start the application
      run: npm start &
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "t_stoyanov"
